config/routes.rb
Rails.application.routes.draw do

  get 'users/new'
  get 'sessions/new'

  resources :programs
	resources :program_requirements
  # resources :program_requirements
  root 'searches#new'
  get   '/root',    to: 'searches#new'
  get   '/result',  to: 'searches#result'
  get   '/support', to: 'searches#support'
  post  '/search',  to: 'searches#search'
  get   '/signup',  to: 'users#new'
  post  '/signup',  to: 'users#create'
  get   '/login',   to: 'sessions#new'
  post  '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :searches
  resources :users
  
  get '/new', to: 'programs#new'
  get '/newpr/:id', to: 'program_requirements#new'
	post '/newpr/:id', to: 'program_requirements#create'

	get '/user', to: 'user#list'
	
	get 'user/list'
	get 'user/show'
	get 'user/new'
	post 'user/create'
	get 'user/edit'
	patch 'user/update'
	get 'user/update'
	get 'user/delete'
	get '/panel/:id', to: 'users#panel'
	post '/user/:id/promote', to: 'users#promote'
	get '/user/:id/promote', to: 'users#show'
  # root 'application#hello'
  
end

app/models/program.rb
class Program < ApplicationRecord
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:name, :abbreviation, :link, :description)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_for(program) do |f| %>
  <% if program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= stylesheet_link_tag "programs.scss" %>

  <div class="container form-inline">
    <div class="col-md-8 col-md-offset-4">
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    
      <div class="field">
        <%= f.label :abbreviation %>
        <%= f.text_field :abbreviation, class: 'form-control' %>
      </div>
    	
    	<div class="field">
        <%= f.label :link %>
        <%= f.text_field :link, class: 'form-control' %>
      </div>
    	
    	<div class="field">
        <%= f.label :description %>
        <%= f.text_area :description, size: "50x5", class: 'form-control' %>
      </div>
    
      <div class="actions">
        <%= f.submit %>
      </div>
      <%= link_to 'Back', programs_path %>
    </div>
    
  </div>
  
  
<% end %>

app/views/programs/edit.html.erb
<!DOCTYPE html>
<html>
	<body>
		<%= render 'layouts/header' %>

		<h1>Editing Program</h1>

		<%= render 'form', program: @program %>
	</body>
</html>

app/views/programs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Programs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Abbreviation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.name %></td>
        <td><%= program.abbreviation %></td>
				<td><%= program.description %></td>
				<td><%= program.link %></td>
        <td><%= link_to 'Show', program %></td>
        <td><%= link_to 'Edit', edit_program_path(program) %></td>
        <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Program', new_program_path %>

app/views/programs/new.html.erb
<!DOCTYPE html>
<html>
	<body>
		<%= render 'layouts/header' %>

		<h1>New Program</h1>

		<%= render 'form', program: @program %>

	</body>
</html>

app/views/programs/show.html.erb
<!DOCTYPE html>
<html>
	<body>
		<%= render 'layouts/header' %>
		<p id="notice"><%= notice %></p>

		<p>
			<strong>Name:</strong>
			<%= @program.name %>
		</p>

		<p>
			<strong>Abbreviation:</strong>
			<%= @program.abbreviation %>
		</p>

		<p>
			<strong>Link:</strong>
			<%= @program.link %>
		</p>
		
		<p>
			<strong>Description:</strong>
			<%= @program.description %>
		</p>

		<%= link_to 'Edit', edit_program_path(@program) %> |
		<%= link_to 'Back', programs_path %>

		<div>
			<p><%= link_to "Add Eligibility Requirements for " + @program.name, {:controller => 'program_requirements', :action => 'new'} %></p>
		</div>
	</body>
</html>