config/routes.rb
Rails.application.routes.draw do

  get 'users/new'
  get 'sessions/new'

  resources :programs
	resources :program_requirements
  # resources :program_requirements
  root 'searches#new'
  get   '/root',    to: 'searches#new'
  get   '/result',  to: 'searches#result'
  get   '/support', to: 'searches#support'
  post  '/search',  to: 'searches#search'
  get   '/signup',  to: 'users#new'
  post  '/signup',  to: 'users#create'
  get   '/login',   to: 'sessions#new'
  post  '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :searches
  resources :users
  
  get '/new', to: 'programs#new'
  get '/newpr/:id', to: 'program_requirements#new'
	post '/newpr/:id', to: 'program_requirements#create'

	get '/user', to: 'user#list'
	
	get 'user/list'
	get 'user/show'
	get 'user/new'
	post 'user/create'
	get 'user/edit'
	patch 'user/update'
	get 'user/update'
	get 'user/delete'
	get '/panel/:id', to: 'users#panel'
	post '/user/:id/promote', to: 'users#promote'
	get '/user/:id/promote', to: 'users#show'
  # root 'application#hello'
  
end

app/models/user.rb
class User < ApplicationRecord

    before_save {email.downcase!}
    validates :first_name, presence: true
    validates :last_name, presence: true
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}, on: :create

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end
  

	def panel
		@user = User.find(params[:id])
		
		@programs = Progam.all
		
		@program = Program.new
		
		@program_requirements = ProgramRequirement.new
	
	end

  
  private
  
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end
	
	

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
		# all new users are not admins by default
		@user.administrator = false
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end
	
	def panel
		@user = User.find(params[:id])
		
		@programs = Program.all
		@requirements = ProgramRequirement.all
		
		@users = User.all
	end
	
	def edit
		@user = User.find(params[:id])
	end
	
	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to root_url, notice: 'User successfully updated!'
		else
			flash.now[:danger] = 'Update failed!'
			redirect_back fallback_location: root_url
		end
	end
	
	def promote
		@user = User.find(params[:id])
		@user.administrator = true
		
		if @user.save
			redirect_to action: "panel", id: session[:user_id]
		else
			flash.now[:danger] = 'Promotion failed!'
			redirect_back fallback_location: root_url
		end
	end
	
	def destroy
		@user = User.find(params[:id])
		@user.destroy
		respond_to do |format|
      format.html { redirect_back fallback_location: root_url, notice: 'Program requirement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
	
  private
  
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :administrator, :password, :password_confirmation)
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
	
	<div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
	
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
	<body>
		<%= render 'layouts/header' %>
		<h1>Editing User</h1>
		<%= render 'form', user: @user %>

		<%= link_to 'Show', @user %> |
		<%= link_to 'Back', users_path %>
	</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <body>
		<%= render 'layouts/header' %>
			<h1>Sign Up</h1>
			
			<div class="container">
					<div class="col-md-8 col-md-offset-4">
							<%= form_for(@user) do |f| %>
									<%= render 'shared/error_messages_signup' %>
									
									<%= f.label :first_name, "First Name" %>
									<%= f.text_field :first_name, class: 'form-control input-restriction' %>
									
									<%= f.label :last_name, "Last Name" %>
									<%= f.text_field :last_name, class: 'form-control input-restriction' %>
									
									<%= f.label :email %>
									<%= f.email_field :email, class: 'form-control input-restriction' %>
									
									<%= f.label :password %>
									<%= f.password_field :password, class: 'form-control input-restriction' %>
									
									<%= f.label :password_confirmation, "Confirmation" %>
									<%= f.password_field :password_confirmation, class: 'form-control input-restriction' %>
									
									<%= f.submit "Create Account", class: "btn btn-primary" %>
							<% end %>
					</div>
			</div>
	</body>
</html>

app/views/users/panel.html.erb
<!DOCTYPE html>
<html>
    <body>
        <%= render 'layouts/header' %>
        
        <div class="container">
            <div class ="center jumbotron">
                <h2>Welcome back, <%= @user.first_name %></h2>
            </div>
        </div>
				
				<div class="container">
					<div class="center jumbotron">
						<h3>Programs</h3>
						<button onClick="this.nextElementSibling.style.display == 'block' ? this.nextElementSibling.style.display='none' : this.nextElementSibling.style.display='block';">Show Programs</button>
						<%# this.nextElementSibling.style.display == 'none' ? this.nextElementSibling.style.display='inline' : this.nextElementSibling.style.display='none'; %>
						<table id="hiddenPrograms">
							<thead>
								<th>ID</th>
								<th>Name</th>
								<th>Abbreviation</th>
								<th>Link</th>
							</thead>
							
							<tbody>
								<% @programs.each do |program| %>
									<tr>
										<td><%= program.id %></td>
										<td><%= program.name %></td>
										<td><%= program.abbreviation %></td>
										<td><a href ="<%= program.link %>"><%= program.link %></a></td>
										<td><%= button_to 'Edit', edit_program_path(program), method: :get%></td>
										<td><%= button_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
									</tr>
								<% end %>
							</tbody>
						</table>
						
						<div>
							<button><%= link_to "Add Program", {:controller => 'programs', :action => 'new'} %></button>
						</div>
					</div>
				</div>
				
				
				<div class="container">
					<div class="center jumbotron">
						<h3>Program Requirements</h3>
						<button onClick="this.nextElementSibling.style.display == 'block' ? this.nextElementSibling.style.display='none' : this.nextElementSibling.style.display='block';">Show Eligibility Requirements</button>
						<table id="hiddenRequirements">
							<thead>
								<tr>
									<th>Program</th>
									<th>Min age</th>
									<th>Max age</th>
									<th>Max Income</th>
									<th>Min Income</th>
									<th>Assets threshold</th>
									<th>Veteran Status Required</th>
									<th>Disabilty Required</th>
									<th>Zip code range</th>
									<th colspan="3"></th>
								</tr>
							</thead>

							<tbody>
								<% @requirements.each do |requirement| %>
									<tr>
										<td><%= requirement.program_id %></td>
										<td><%= requirement.min_age %></td>
										<td><%= requirement.max_age %></td>
										<td><%= requirement.max_income %></td>
										<td><%= requirement.min_income %></td>
										<td><%= requirement.assets_threshold %></td>
										<td><%= requirement.veteran %></td>
										<td><%= requirement.disabled %></td>
										<td><%= requirement.zip_code_range_start %> - <%= requirement.zip_code_range_end %></td>
										<td><%= button_to 'Edit', edit_program_requirement_path(requirement), method: :get %></td>
										<td><%= button_to 'Destroy', requirement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
									</tr>
								<% end %>
							</tbody>
						</table>
						<%# Removed 'add program requirements' button. Users should add requirements immediately after adding a program %>
					</div>
				</div>
			<% if @user.administrator %>	
				<div class="container">
					<div class="center jumbotron">
						<h3>Users</h3>
						<button onClick="this.nextElementSibling.style.display == 'block' ? this.nextElementSibling.style.display='none' : this.nextElementSibling.style.display='block';">Show Users</button>
						<table id="hiddenUsers">
							<thead>
								<th>Name</th>
								<th>Email</th>
								<th>Admin Privelages?</th>
							</thead>
							<tbody>
								<% @users.each do |user| %>
									<tr>
										<td><%= user.first_name %> <%= user.last_name %></td>
										<td><%= user.email %></td>
										<td><%= user.administrator %></td>
										<td><%= button_to "Make Admin", {:action => "promote", id: user.id} %></td>
										<td><%= button_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure you want to delete this user?'} %></td>
									</tr>
								<% end %>
							</tbody>
						</table>
					</div>
          <div>
            <button><%= link_to "Add User", {:action => 'new'} %></button>
					</div>
				</div>
			<% end %>	
    </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
	<body>
			<%= render 'layouts/header' %>
			<div class="container">
					</br>
					</br> 
					<!--  Temporary fix with line breaks -->
					<div class="col-md-6 col-md-offset-3">
							<h2>Welcome, <%= @user.first_name %></h2>
					</div>
			</div>
			<%= @user.first_name %>, <%= @user.email %>
	</body>
</html>