config/routes.rb
Rails.application.routes.draw do

  get 'users/new'
  get 'sessions/new'

  resources :programs
	resources :program_requirements
  # resources :program_requirements
  root 'searches#new'
  get   '/root',    to: 'searches#new'
  get   '/result',  to: 'searches#result'
  get   '/support', to: 'searches#support'
  post  '/search',  to: 'searches#search'
  get   '/signup',  to: 'users#new'
  post  '/signup',  to: 'users#create'
  get   '/login',   to: 'sessions#new'
  post  '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :searches
  resources :users
  
  get '/new', to: 'programs#new'
  get '/newpr/:id', to: 'program_requirements#new'
	post '/newpr/:id', to: 'program_requirements#create'

	get '/user', to: 'user#list'
	
	get 'user/list'
	get 'user/show'
	get 'user/new'
	post 'user/create'
	get 'user/edit'
	patch 'user/update'
	get 'user/update'
	get 'user/delete'
	get '/panel/:id', to: 'users#panel'
	post '/user/:id/promote', to: 'users#promote'
	get '/user/:id/promote', to: 'users#show'
  # root 'application#hello'
  
end

app/models/program_requirement.rb
class ProgramRequirement < ApplicationRecord
	belongs_to :program
	validates_inclusion_of :disabled, :in => [true, false]
	validates_inclusion_of :veteran, :in => [true, false]
	validates :max_income, presence: true
	validates :zip_code_range_start, presence: true
	validates :zip_code_range_end, presence: true
	validates :max_age, presence: true
	validates :min_age, presence: true
end

app/controllers/program_requirements_controller.rb
class ProgramRequirementsController < ApplicationController
  before_action :set_program_requirement, only: [:show, :edit, :update, :destroy]

  # GET /program_requirements
  # GET /program_requirements.json
  def index
    @program_requirements = ProgramRequirement.all
  end

  # GET /program_requirements/1
  # GET /program_requirements/1.json
  def show
  end

  # GET /program_requirements/new
  def new
    @program_requirement = ProgramRequirement.new
		@program = Program.find(params[:id])
  end

  # GET /program_requirements/1/edit
  def edit
  end

  # POST /program_requirements
  # POST /program_requirements.json
  def create
    @program_requirement = ProgramRequirement.new(program_requirement_params)
		@program = Program.find(params[:id])
		@program_requirement.program = @program
		
		@program_requirement.disabled = params[:disabled]
		@program_requirement.veteran = params[:veteran]

    respond_to do |format|
      if @program_requirement.save
        format.html { redirect_to @program_requirement, notice: 'Program requirement was successfully created.' }
        format.json { render :show, status: :created, location: @program_requirement }
      else
        format.html { render :new }
        format.json { render json: @program_requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /program_requirements/1
  # PATCH/PUT /program_requirements/1.json
  def update
		if !@program_requirement.veteran.nil?
			@program_requirement.veteran = params[:veteran]
		end
		if !@program_requirement.disabled.nil?
			@program_requirement.disabled = params[:disabled]
		end
    respond_to do |format|
      if @program_requirement.update_attributes(program_requirement_params)
        format.html { redirect_to @program_requirement, notice: 'Program requirement was successfully updated.' }
        format.json { render :show, status: :ok, location: @program_requirement }
      else
        format.html { render :edit }
        format.json { render json: @program_requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /program_requirements/1
  # DELETE /program_requirements/1.json
  def destroy
		@program_requirement = ProgramRequirement.find(params[:id])
    @program_requirement.destroy
    respond_to do |format|
      format.html { redirect_to program_requirements_url, notice: 'Program requirement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program_requirement
      @program_requirement = ProgramRequirement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_requirement_params
      params.require(:program_requirement).permit(:min_age, :max_age, :max_income, :min_income, :assets_threshold, :veteran, :disabled, :zip_code_range_start, :zip_code_range_end)
    end
end

app/helpers/program_requirements_helper.rb
module ProgramRequirementsHelper
end

app/views/program_requirements/_form.html.erb
<%= form_for(program_requirement) do |f| %>
  <% if program_requirement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(program_requirement.errors.count, "error") %> prohibited this program_requirement from being saved:</h2>

      <ul>
      <% program_requirement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
		<div class="container">
      <div class="col-md-6 col-md-offset-3 form-inline">
        <div class="field">
          <%= f.label :min_age %>
          <%= f.number_field :min_age %>
        </div>
      
        <div class="field">
          <%= f.label :max_age %>
          <%= f.number_field :max_age %>
        </div>
      
        <div class="field">
          <%= f.label :max_income %>
          <%= f.number_field :max_income %>
        </div>
      
      	<div class="field">
          <%= f.label :min_income %>
          <%= f.number_field :min_income %>
        </div>
      	
        <div class="field">
          <%= f.label :assets_threshold %>
          <%= f.number_field :assets_threshold %>
        </div>
      
      	<div class="field">
      		<strong>Veteran Status Required</strong>
      		</br>
      		<strong>Current status: <%= program_requirement.veteran %></strong>
      		</br>
      		<%= radio_button_tag(:veteran, false) %>
      		<%= label_tag(:veteran_false, "No") %>
      		<%= radio_button_tag(:veteran, true) %>
      		<%= label_tag(:veteran_true, "Yes") %>
      		</br>
      	</div>
      	<iv class="field">
      	<strong>Disability Required -- Patient has to have been collecting disability benefits for at least 2 years</strong>
      	</br>
      		<strong>Current status: <%= program_requirement.disabled %></strong>
      	</br>
      	<%= radio_button_tag(:disabled, false) %>
      	<%= label_tag(:disabled_false, "No") %>
      	<%= radio_button_tag(:disabled, true) %>
      	<%= label_tag(:disabled_true, "Yes") %>
      	</br>
      
        <div class="field">
          <%= f.label :zip_code_range_start %>
          <%= f.number_field :zip_code_range_start %>
        </div>
      	
      	<div class="field">
          <%= f.label :zip_code_range_end %>
          <%= f.number_field :zip_code_range_end %>
        </div>
      
        <div class="actions">
          <%= f.submit %>
        </div>
        
        <%= link_to 'Show', @program_requirement %> |
    		<%= link_to 'Back', program_requirements_path %>
      </div>
    </div>
<% end %>

app/views/program_requirements/edit.html.erb
<!DOCTYPE html>
<html>
	<body>
		<%= render 'layouts/header' %>
		<h1>Editing Program Requirement</h1>
		<%= render 'form', program_requirement: @program_requirement %>

		<!--<%= link_to 'Show', @program_requirement %> |-->
		<!--<%= link_to 'Back', program_requirements_path %>-->
	</body>
</html>

app/views/program_requirements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Program Requirements</h1>

<table>
  <thead>
    <tr>
      <th>Min age</th>
      <th>Max age</th>
      <th>Max Income</th>
			<th>Min Income</th>
      <th>Assets threshold</th>
      <th>Veteran</th>
      <th>Disabled</th>
      <th>Zip code Range</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @program_requirements.each do |program_requirement| %>
      <tr>
        <td><%= program_requirement.min_age %></td>
        <td><%= program_requirement.max_age %></td>
        <td><%= program_requirement.max_income %></td>
				<td><%= program_requirement.min_income %></td>
        <td><%= program_requirement.assets_threshold %></td>
        <td><%= program_requirement.veteran %></td>
        <td><%= program_requirement.disabled %></td>
        <td><%= program_requirement.zip_code_range_start %> - <%= program_requirement.zip_code_range_end %></td>
        <td><%= link_to 'Show', program_requirement %></td>
        <td><%= link_to 'Edit', edit_program_requirement_path(program_requirement) %></td>
        <td><%= link_to 'Destroy', program_requirement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Program Requirement', new_program_requirement_path %>

app/views/program_requirements/new.html.erb
<!DOCTYPE html>
<html>
    <body>
			<%= render 'layouts/header' %>
        <h1>New Program Requirements for <%= @program.name %></h1>
        
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <%= form_for @program_requirement, url: {action: "create"} do |f| %>
                    <%= f.label :max_income, "Max income (Percentage of federal poverty level)" %>
                    <%= f.number_field :max_income, class: 'form-control' %>
                    
                    <%= f.label :min_income, "Minimun income threshold, if applicable -- also as a percentage of federal poverty level" %>
                    <%= f.number_field :min_income, class: 'form-control' %>
                    
										<%= f.label :assets_threshold, "Total assets limit" %>
                    <%= f.number_field :assets_threshold, class: 'form-control' %>
										
                    <%= f.label :min_age, "Minimum age" %>
                    <%= f.number_field :min_age, class: 'form-control' %>
                    
										<%= f.label :max_age, "Maximum age" %>
                    <%= f.number_field :max_age, class: 'form-control' %>
                    
										Range of eligible zip codes
										
										<%= f.label :zip_code_range_start, "Range start point" %>
                    <%= f.text_field :zip_code_range_start, class: 'form-control' %>
										
										<%= f.label :zip_code_range_end, "Range end point" %>
                    <%= f.text_field :zip_code_range_end, class: 'form-control' %>
										
										<strong>Veteran Status Required</strong>
										</br>
										<%= radio_button_tag(:veteran, false) %>
										<%= label_tag(:veteran_false, "No") %>
										<%= radio_button_tag(:veteran, true) %>
										<%= label_tag(:veteran_true, "Yes") %>
										</br>
										
										<strong>Disability Required -- Patient has to have been collecting disability benefits for at least 2 years</strong>
										</br>
										<%= radio_button_tag(:disabled, false) %>
										<%= label_tag(:disabled_false, "No") %>
										<%= radio_button_tag(:disabled, true) %>
										<%= label_tag(:disabled_true, "Yes") %>
										</br>
										
                    <%= f.submit "Submit", class: "btn btn-primary" %>
                <% end %>
            </div>
        </div>
    </body>
    
</html>

app/views/program_requirements/show.html.erb
<!DOCTYPE html>
<html>
	<body>
		<%= render 'layouts/header' %>
		<p id="notice"><%= notice %></p>

		<p>
			<strong>Min age:</strong>
			<%= @program_requirement.min_age %>
		</p>
		<div class="help-tip">
			<p>This is the inline help tip! It can contain all kinds of HTML. Style it as you please.</p>
		</div>
		<p>
			<strong>Max age:</strong>
			<%= @program_requirement.max_age %>
		</p>

		<p>
			<strong>Min Income:</strong>
			<%= @program_requirement.min_income %>
		</p>

		<p>
			<strong>Max Income:</strong>
			<%= @program_requirement.max_income %>
		</p>


		<p>
			<strong>Assets threshold:</strong>
			<%= @program_requirement.assets_threshold %>
		</p>

		<p>
			<strong>Veteran:</strong>
			<%= @program_requirement.veteran %>
		</p>

		<p>
			<strong>Disabled:</strong>
			<%= @program_requirement.disabled %>
		</p>

		<p>
			<strong>Zip code range:</strong>
			<%= @program_requirement.zip_code_range_start %> - <%= @program_requirement.zip_code_range_end %>
		</p>

		<%= link_to 'Edit', edit_program_requirement_path(@program_requirement) %> |
		<%= link_to 'Back', program_requirements_path %>
	</body>
</html>