config/routes.rb
Rails.application.routes.draw do

  get 'users/new'
  get 'sessions/new'

  resources :programs
	resources :program_requirements
  # resources :program_requirements
  root 'searches#new'
  get   '/root',    to: 'searches#new'
  get   '/result',  to: 'searches#result'
  get   '/support', to: 'searches#support'
  post  '/search',  to: 'searches#search'
  get   '/signup',  to: 'users#new'
  post  '/signup',  to: 'users#create'
  get   '/login',   to: 'sessions#new'
  post  '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :searches
  resources :users
  
  get '/new', to: 'programs#new'
  get '/newpr/:id', to: 'program_requirements#new'
	post '/newpr/:id', to: 'program_requirements#create'

	get '/user', to: 'user#list'
	
	get 'user/list'
	get 'user/show'
	get 'user/new'
	post 'user/create'
	get 'user/edit'
	patch 'user/update'
	get 'user/update'
	get 'user/delete'
	get '/panel/:id', to: 'users#panel'
	post '/user/:id/promote', to: 'users#promote'
	get '/user/:id/promote', to: 'users#show'
  # root 'application#hello'
  
end

app/views/layouts/_footer.html.erb
<footer class="footer-custom">
    <div class="container">
        <h4 class="footer-text">University of Pittsburgh School of Pharmacy</h3>
				<p class="footer-text">
					3501 Terrace St Pittsburgh, PA 15261
					<br>
					412-624-5240
				</p>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-static-top navbar-inverse">
    <div class="container">
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",    root_path %></li>
            <li><%= link_to "About", support_path %></li>
            <% if logged_in? %>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Settings", '#' %></li>
												<li class ="divider"></li>
                        <li><%= link_to "Edit Profile", edit_user_path(session[:user_id])%></li>
                        <li class ="divider"></li>
                        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                    </ul>
                </li>
								<li><%= link_to "Control Panel", {:controller => "users", :action => "panel", id: session[:user_id]} %></li>
            <% else %>
                <li><%= link_to "Log in", login_path %></li>
            <% end %>
        </ul>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Capstone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>